### ISSUE TITLE
Incorrect monthly returns?

### ISSUE THREAD

**Issue by LuisSousaSilva** [ranaroussi/monthly-returns-heatmap#2]
Hi, 

In the last couple of months i've been using this small but great library. However, this weekend when i was doing some further EDA i noticed a discrepancy between my monthly returns and yours.

I went to morningstar to check the real (industrial grade??) monthly returns on SPY and they matched with mine, even if very similar to yours. It seems to me that you are summing daily returns, instead of using cumsum() or using a more simple approach as i did.

I took the liberty to make the necessary changes to your code so that the output would be the same as morningstar's (and as financial theory dictates).

Where you have:
```
def get(returns):

    # resample to business month
    returns = returns.resample('BMS').sum()
```

I changed to:
```
def get(quotes):

    # resample quotes to business month
    monthly_quotes = quotes.resample('BMS').last()
    
    # get monthly returns
    returns = monthly_quotes.pct_change()
```

The changes i made make the function work with quotes, not returns, as it is easier. You can reproduce a map with my code and another with yours and compare to Morningstar SPY monthly performance. I will also willingly share a .ipynb with reproducible code and outputs, if necessary.

I shared this for your review.

Thank you,

_Luis Silva_

P.S. For my personal use i also included `center=0` on the call for sns.heatmap, as i had some slightly negative values (i.e. -0.05) showing as green.

**Comment by ranaroussi** [comment]
I've updated the code to use a more accurate monthly return calculation albait using a different approach than yours. I've also included the option to use price data instead of returns by passing ``is_prices=True`` to either ``get()`` or ``plot()``.

LMK if this works out for you.

PS. This post may be relevant :)
https://quantdare.com/calculate-monthly-returns-with-pandas/

**Comment by ranaroussi** [comment]
I've added this "secret" method which you can use, that provided me accurate results:

```python
def sum_returns(returns, groupby):
    def returns_prod(data):
        return (data + 1).prod() - 1
    return returns.groupby(groupby).apply(returns_prod)

# EOM
sum_returns(df, df.index.monthly)

# EOY
sum_returns(df, (df.index.year, df.index.monthly))
```

**Comment by LuisSousaSilva** [comment]
> I've updated the code to use a more accurate monthly return calculation 

Everything seems to be working correctly now and the monthly returns match the "true" returns.

> albait using a different approach than yours.

Of course. My approach is not only rudimentary (I'm not a very good programmer i'm afraid) but would also break previous code. 

> I've also included the option to use price data instead of returns by passing is_prices=True to either get() or plot().

This being unnecessary extra work i kind of feel more thankful to you.

> PS.  This post may be relevant :) https://quantdare.com/calculate-monthly-returns-with-pandas/

I actually use quotes.resample('BM').last() in my code. Don't know how that mistake (of using BMS) slipped by me. Guess i was too focused on the output. Will also probably also change to 'asfreq'. It actually seems more appropriate.

Thanks for the resource. That site/blog seems awesome.

> I've added this "secret" method which you can use, that provided me accurate results:

Once again thank you.

The update seems it's still not on pip so i'm still using the code directly for the time being. Will be checking regularly to see if the update is up ;-)

P.S. Didn't realized you were the one behind the fix-yahoo-finance package this spring. Awesome work.
